# Generated by Django 4.1.3 on 2023-01-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicidad_alter_cliente_al_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
