# Generated by Django 4.1.3 on 2023-01-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nombre_publicidad_nombre_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
