# Generated by Django 4.1.3 on 2022-12-18 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cedula', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('celular', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=500, null=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin status')),
                ('is_client', models.BooleanField(default=False, verbose_name='client status')),
                ('is_operator', models.BooleanField(default=False, verbose_name='operator status')),
                ('is_gerente', models.BooleanField(default=False, verbose_name='gerente status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('al_dia', models.IntegerField()),
                ('servicio_activo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gerente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operator', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('celular', models.IntegerField()),
                ('direccion', models.CharField(max_length=500)),
                ('salario', models.IntegerField()),
                ('password_login', models.CharField(max_length=100)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_rep', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_expedicion', models.DateField()),
                ('inicio_plazo', models.DateField()),
                ('fin_plazo', models.DateField()),
                ('pagado', models.BooleanField()),
                ('fecha_pago_efectuado', models.DateField(auto_now=True)),
                ('estrato_economico', models.IntegerField()),
                ('consumo_en_kwh', models.IntegerField()),
                ('total_pagar', models.IntegerField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_fac', to='core.cliente')),
                ('operador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_id_fac', to='core.operator')),
            ],
        ),
    ]
