# Generated by Django 4.1.3 on 2023-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('publicidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('imagen', models.ImageField(default='', upload_to='publicidad')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='al_dia',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servicio_activo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
